# Qwen 32B GPTQModel 量化配置
quantization:
  bits: 4
  group_size: 128
  damp_percent: 0.01
  desc_act: false
  sym: true
  true_sequential: true
  tokenizer: Qwen/Qwen2.5-32B-Instruct
  block_name_to_quantize:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj

batch_size: 4
