quantization:
  bits: 4
  group_size: 128
  v2: true
  dynamic:
    ".*attention.*": 
      bits: 4
    ".*mlp.*": 
      bits: 4
    "-:.*lm_head.*": {}

calibration_dataset:
  name: "wikitext"
  config: "wikitext-2-v1"
  split: "train"
  text_column: "text"
  samples: 64  
batch_size: 1   
auto_gc: true
buffered_fwd: false
